#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    atonSelector,   sensorPotentiometer)
#pragma config(Sensor, in2,    powerExpander,  sensorAnalog)
#pragma config(Sensor, in5,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in6,    lineMiddle,     sensorLineFollower)
#pragma config(Sensor, in7,    lineRight,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  liftArmEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  liftArmDown,    sensorTouch)
#pragma config(Sensor, dgtl4,  intakeFull,     sensorTouch)
#pragma config(Sensor, dgtl5,  ballLift,       sensorDigitalOut)
#pragma config(Sensor, dgtl6,  middleRightBackup, sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  middleLeftBackup, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port2,           middleLeft,    tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           intakeLeft,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           liftTopRight,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           liftBottomRight, tmotorVex393, openLoop)
#pragma config(Motor,  port6,           liftBottomLeft, tmotorVex393, openLoop)
#pragma config(Motor,  port7,           liftTopLeft,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           intakeRight,   tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           middleRight,   tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 0)
#pragma config(Motor,  port10,          backRight,     tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 0)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "globalVariables.h"
#include "lcdFunctions.h"
#include "functions.h"
#include "tasks.h"
#include "autonomousSelector.h"
#include "autonomous.h"
#include "driverControl.h"
#include "programmingSkills.h"

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"

void pre_auton()
{
	writeDebugStreamLine("INFO: Pre_Auton Started");
	if(bResetFromWatchdogTimeout)
	{
		writeDebugStreamLine("ERROR: Watchdogtimeout Caused Restart");
	}
	if(bIfiRobotDisabled && !bResetFromWatchdogTimeout)
	{
		writeDebugStreamLine("INFO: Starting Battery Check");
		batteryCheck();
		writeDebugStreamLine("INFO: Battery Check Done");
		writeDebugStreamLine("INFO: Starting Autonomous Selector");
		autonNumber = autonomousSelector();
		writeDebugStreamLine("INFO: Autonomous Selector Returned %d", autonNumber);
	}
	//resetEveryThing();
	bStopTasksBetweenModes = true;
	writeDebugStreamLine("INFO: Pre_Auton Done");
}

task autonomous()
{
	writeDebugStreamLine("INFO: Autonomous Started");
	StartTask(liftArmLimiter);

	writeDebugStreamLine("INFO: Autonomous Done");
}

task usercontrol()
{
	writeDebugStreamLine("INFO: Driver_Control Started");
	driverControl(true);
}
